[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path = 'forge-cache'
solc_version = '0.8.10'
optimizer = true
optimizer_runs = 99999
fs_permissions = [{ access = "read", path = "./addresses.json"}]

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"

[etherscan]
polygon = { key = "${BLOCK_EXPLORER_KEY}" }
mumbai = { key = "${BLOCK_EXPLORER_KEY}" }

[fuzz]
runs = 10000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
